OPTIONS=-Wall -Werror -x c -I../src -I$(UNITY_PATH)src -o


build: test_fixed_point_complex.c
	gcc $(OPTIONS) test_fixed_point_complex test_fixed_point_complex.c -L~/workspace/c_project/src -lfixed_point_complex.o
